"""add_achievement_description

Revision ID: 347d13afbfbd
Revises: b6391d739110
Create Date: 2026-02-24 20:19:22.155103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347d13afbfbd'
down_revision: Union[str, None] = 'b6391d739110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'description')
    # ### end Alembic commands ###
